# 配置数据源
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/lyf?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: lyf
      password: 1234
   jpa:
# 自动生产DDL语句（数据定义语言），用于实现表结构自动创建
      generate-ddl: true
# 显示每个SQL在日志里面
      show-sql: true
   redis:
      host: 127.0.0.1
      port: 6379
      database: 6
